repos:
    - repo: local
      hooks:
          - id: isort
            name: sort python imports
            entry: isort --settings-path setup.cfg
            language: system
            files: '.*\.py'
            pass_filenames: true
          - id: black
            name: black (format)
            entry: black
            language: system
            files: '.*\.py'
            pass_filenames: true
          - id: unittest
            name: run unittests
            entry: bash -c "pytest -v"
            language: system
            files: '.*\.py'
            pass_filenames: false
          - id: pylint
            name: lint python code (pylint)
            entry: >-
                python -m pylint
                --rcfile=setup.cfg
            language: system
            files: '.*\.py'
            pass_filenames: true
