dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install --upgrade pip pipenv
  - pipenv lock -r -d > requirements.txt
  - pipenv lock -r  >> requirements.txt
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - isort -c
  - black --check .
  - pyroma .
  - pylint --rcfile=setup.cfg ddionrails_datapackage tests
  - pytest -rf --cov