metadata:
  # Recommended Properties
  name: gip
  id: ""
  licenses: []

  # Optional Properties
  title: ""
  description: ""
  homepage: ""
  version:  ""
  sources:  []
  contributors: []
  keywords: []
  image: ""
  created: ""

files:
  # Select which files to use
  - questions_images.csv