name: Check-Data-Compliance

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          pip install --upgrade pip pipenv
          pipenv lock -r -d > requirements.txt
          pip install -r requirements.txt
          pip install .
      - name: Test Format
        run: |
          isort -c
          black --check .
      - name: Test Smells
        run: pyroma .
      - name: Lint
        run: pylint --rcfile=setup.cfg ddionrails_datapackage tests
